# Generated by Django 4.1.6 on 2023-02-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123)),
                ('position', models.CharField(max_length=123)),
                ('date_employment', models.DateField()),
                ('salary', models.FloatField()),
            ],
        ),
    ]
